CREATE TABLE role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   role VARCHAR(255),
   CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT NOT NULL,
   created_by VARCHAR(255),
   created_date TIMESTAMP,
   last_modified_by VARCHAR(255),
   last_modified_date TIMESTAMP,
   client_id VARCHAR(255),
   password VARCHAR(255),
   role_id BIGINT,
   first_name VARCHAR(255),
   last_name VARCHAR(255),
   twilio_number VARCHAR(255),
   CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_clientid UNIQUE (client_id);

ALTER TABLE users ADD CONSTRAINT uc_users_twilionumber UNIQUE (twilio_number);

ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);
